title: "Deep Learning Practices"
author: "Yash Mishra"
copyright: "2025"
logo: ""
language: "en"
execute:
  execute_notebooks: "auto"
  
repository:
  url: https://github.com/the-y9/Deep-Learning-Practices

html:
  use_issues_button: true
  use_repository_button: true
